services:

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433

    environment:
      - MSSQL_SA_PASSWORD=My@Test@Password1
    command: ["/opt/mssql/bin/sqlservr", "--accept-eula", "--reset-sa-password"]

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test


  db2:
    image: icr.io/db2_community/db2:11.5.8.0
    ports:
       - "50000:50000"
    environment:
      LICENSE: accept
      DB2INSTANCE: db2inst1
      DB2INST1_PASSWORD: test
      DBNAME: test

  dev:
    build: docker/dev
    volumes:
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Allows accessing dbs through the port forwardings. dev container behaves like host for networking
    network_mode: host
