name: Rust

on: [push, pull_request]

jobs:
  build:
    name: Build on 64Bit Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.52.1"
          default: true
          override: true

      - name: Build
        run: cargo build --release

